### ISSUE TITLE
Request to add several more sites

### ISSUE THREAD

**Issue by nitrohorse** [rimu/no-qanon#1]
Hey, thanks for creating this list! I've also :+1:'d your [request to add it to NextDNS](https://github.com/nextdns/metadata/issues/423). Would be great to get this added to [filterlists.com](https://github.com/collinbarrett/FilterLists) to be more easily findable. Additionally, I found https://github.com/antifa-n/pihole which was last updated months ago and maybe worth comparing against to pull any missing domains.

A couple other sites worth considering adding:
- americannaziparty.com
- atomwaffendivision.org
- dailystormer.red
- thedonald.win

**Comment by rimu** [comment]
Thanks nitrohorse, very helpful!
