### ISSUE TITLE
Why are VPNs and proxies blocked?

### ISSUE THREAD

**Issue by AndrewDaws** [rimu/no-qanon#21]
Why do you have a large number of legitimate VPN and proxy services in the block lists?
- expressvpn.com
- nordvpn.com
- protonvpn.com
- etc

These services have plenty of legitimate uses (bypass geo-restrictions for streaming services, check prices elsewhere, privacy from nosy ISP or public WiFi, bypass nation-state or company imposed censorship, etc) that have zero reason to be blocked in what is supposed to be a blocklist for QAnon, conspiracies, and fakenews.

Yes, one could argue that a VPN or proxy could be used to bypass this blocklist to still reach those very sites, but that becomes a game of whack-a-mole for blocking each VPN or proxy provider, and there are already lists out there for exactly this purpose.

In my opinion this is overreach and beyond the scope of this blocklist. If you want to block bypass methods, either use one of the existing lists out there, or put it into it's own blocklist separate from the main list.

**Comment by ghost** [comment]
i have a list of known vpn under my sleeve i will list them and add them in a "mistake" pull request (maybe a mistake during the add of the domain),

**Comment by ghost** [comment]
@AndrewDaws pull request done : https://github.com/rimu/no-qanon/pull/22
edit : thanks for the report anyway 👍

**Comment by AndrewDaws** [comment]
For anyone who does want to block bypass methods, here is a good list containing VPNs, proxies, DNS, etc.
https://github.com/nextdns/metadata/blob/master/parentalcontrol/bypass-methods

**Comment by rimu** [comment]
I agree. Let's remove them from the list.
