### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by vvoww** [rimu/no-qanon#25]
Hi I stumbled upon your list a couple weeks ago, now that I'm considering to deploy it, got this question.

What license is this project using? I myself am a strong and passionate proponent of FOSS (so excuse me the following nitpicking :) and to my understanding a failure to include any legal license defaults the work to a proprietary license, basically "all rights reserved." This makes any at scale deployments problematic, especially when we are talking about anything but private environments; making PRs and publishing changes etc.

Now I understand it was probably never your intention to impose any restrictions upon anybody wishing to use your list (correct me if I'm wrong), but I'd be happier (and have fewer questions asked) if this was set in stone with a FOSS-type license (we're on Github after all). Not least because I consider to deploy this list for my users (as well as for my own sanity and less wasted time on these sites).

Couple years ago the [anti-fascist MIT license](https://github.com/jamiebuilds/anti-fascist-mit-license) had been making the rounds, sounds like a perfect complement for this occasion.

What are your thoughts and what's the general usage terms until then? Thanks

**Comment by rimu** [comment]
Ha, that license is fantastic. I've added it now.

Thanks!
