### ISSUE TITLE
Suspected incorrect inclusion of discord.com/discordapp.com

### ISSUE THREAD

**Issue by MoralCode** [rimu/no-qanon#3]
It appears as though the domains (discord.com and discordapp.com) for Discord (the popular chat app primarily designed for gaming and similar communities) may have been incorrectly included in these blocklists.

While Discord does have the potential to be used by hate groups (as does any social media platform), their [community guidelines](https://discord.com/guidelines) specifically disallow this sort of behavior (emphasis mine):
> 1. Do not organize, participate in, or encourage harassment of others. Disagreements happen and are normal, but continuous, repetitive, or severe negative comments may cross the line into harassment and are not okay.
> 2. **Do not organize, promote, or coordinate servers around hate speech. It’s unacceptable to attack a person or a community based on attributes such as their race, ethnicity, national origin, sex, gender, sexual orientation, religious affiliation, or disabilities.**
> 3. Do not make threats of violence or threaten to harm others. This includes indirect threats, as well as sharing or threatening to share someone’s private personal information (also known as doxxing).
> ...

In my experience, Discord also includes a good selection of options to allow both server moderators/admins and individual users to moderate their own experiences on the platform (such as banning and blocking users).

If there is a reason that Discord has been included in these lists, I would be interested to know as my experience with the app has been quite positive overall and i have not yet seen or heard anything about the app that would suggest that it has anything to do with QAnon, conspiracy theories, fake news, or nazis.

**Comment by rimu** [comment]
Early on in my research I found some people using Discord, but none since. It appears to be an isolated incident, so I've removed discord from the list.

Thanks for bringing this up.
