### ISSUE TITLE
Add domains from the NY shooter manifesto

### ISSUE THREAD

**Issue by Gitoffomalawn** [rimu/no-qanon#38]
Hi,

Consider adding these following sites to your conspiracy blocklist:

- `worldtruthvideos.website`
- `dailyarchives.org`
- `dailystormer.cn`

There are websites that have contributed to the recent NY shooting by spreading conspiracy theories.

**Comment by rimu** [comment]
Thanks for that.

However none of those websites are working.

**Comment by Gitoffomalawn** [comment]
I must admit I hadn't checked them beforehand. However, the last one (`dailystormer.cn`) does seem to be working as per my check just a minute ago.

**Comment by rimu** [comment]
Oh yeah, that one's back.
Thanks, I've added it now.
