### ISSUE TITLE
German sites

### ISSUE THREAD

**Issue by nichu42** [rimu/no-qanon#40]
I don't know if you also add sites in other languages than English. If you do, you might want to consider adding
||Pravda-TV.com^
||Compact-Online.de^
||JournalistenWatch.com^
||Deutschland-Kurier.org^
||EpochTimes.de^
||SputnikNews.com^
||rt.com^
||kopp-verlag.de^
||Noch.info^
||halle-leaks.de^
||deutsche-wirtschafts-nachrichten.de^
||zentrum-der-gesundheit.de^
||netzfrauen.org^
||AllEinKlang.tv^
||bewusst.tv^
||expresszeitung.com^
||kreuz.net^
||pi-news.net^
||quer-denken.tv^
||rubikon.news^
||Volksbetrug.net^
||kla.tv^
||xn--rzte-fr-aufklrung-pqbn68b.de^
||aerztefueraufklaerung.de^
||corona-aufklaerung.tv^
||wahrheiten.org^
||neopresse.com^
||corona-ausschuss.de^
||uncutnews.ch^

**Comment by rimu** [comment]
Very good, thanks!

**Comment by nichu42** [comment]
Two more from Germany...
||https://punkt-preradovic.com/^
||https://apolut.net/^
