### ISSUE TITLE
no `.ua` websites?

### ISSUE THREAD

**Issue by Nakilon** [rimu/no-qanon#43]
I am Ukrainian. Ukraine is the only currently known to me real neo-nazi state. It is like this since 2014 when the government has started terroristic acts in Eastern and Sourthern regions and militarizing neo-nazi battalions. You may realize how carefully the English language mass media was hiding the whole 8 years long war and in fact a genocide by just asking yourself when you've heard about the "Azov battalion" the first time.
Anyway, I just wonder why I don't see the `.ua` websites listed while all the state and private media are turned into pure neo-fascist and Hitler-supporting propaganda years ago. Are you just not aware or is it any hidden policy in this repo? I would probably find some time to gather some `.ua` links to be added.

**Comment by nichu42** [comment]
The not so hidden policy of this repo is to block fake news. Such as that Ukraine is a neo-nazi state.

**Comment by Nakilon** [comment]
lmao, ok

**Comment by Nakilon** [comment]
Just to prove that you in Germany or wherever definitely know better, can you list the surnames of presidents of Ukraine without googling?

**Comment by contributorpw** [comment]
@Nakilon, stop testing! It can break if extreme checks are made on it.

**Comment by contributorpw** [comment]
@Nakilon, I see a solid list. It may be fine.

It's strange that no one suggested `.ua` sites. Isn't there a tabloid fake press? By the way, a ukrainian minister was fired there. She claimed that there was child abuse by the soldiers. But the whole country can't find evidence of this. Isn't this fake?

`hypocrisy`

**Comment by rimu** [comment]
no
