### ISSUE TITLE
Remove nypost.com

### ISSUE THREAD

**Issue by Gitoffomalawn** [rimu/no-qanon#47]
Your list currently blocks `nypost.com` and `www.nypost.com`, which is a legitimate news source. Please remove it from the list.

**Comment by rimu** [comment]
Organizations like this are a difficult decision. While not overtly fascist or conspiracy-laden, they are total pieces of sh*t who can get in the sea. So I'm torn.

https://en.wikipedia.org/wiki/New_York_Post#Accusations_of_racism
https://en.wikipedia.org/wiki/New_York_Post#Hunter_Biden_laptop_story
https://en.wikipedia.org/wiki/New_York_Post#Other_controversies

I guess if nypost is included then I'd also need to include Fox News.

**Comment by Gitoffomalawn** [comment]
> Organizations like this are a difficult decision. While not overtly fascist or conspiracy-laden, they are total pieces of sh*t who can get in the sea. So I'm torn.

Fair enough, although that would include most (if not all) of the US government, most Fortune 500 companies, police departments, and many more. 

Seeing as most people probably use this list for what its name suggests (getting rid of Q and other conspiracy bullshit), it's probably best to keep it focused on that. 

You could always make another list for the "total pieces of sh*t who can get in the sea" category. That way, people know what they're getting into. 

> I guess if nypost is included then I'd also need to include Fox News.

And WaPo, and probably every other news organization under the sun. NY Post is certainly not the only news organization burdened by controversies, and certainly not the worst of those that are.
