### ISSUE TITLE
False positive, jurneywrites.wordpress.com

### ISSUE THREAD

**Issue by joelkp** [rimu/no-qanon#51]
Said blog is an anti-QAnon and general anti-cult site, not a proponent of those things. (It also hosts [a copy of a 1972 paper on cults by Colin Campbell](https://jurneywrites.wordpress.com/2021/11/27/the-cult-the-cultic-milieu-and-secularization/) otherwise rare online, which is how I ended up finding it.)

I also have some suggestions for things to add, but I guess that's best dealt with separately.

**Comment by rimu** [comment]
I've removed it. Thank you very much!
