### ISSUE TITLE
Why is commondreams.org in a no-qanon blacklist???

### ISSUE THREAD

**Issue by ScarylePoo** [rimu/no-qanon#56]
https://github.com/rimu/no-qanon/blob/9041c43819836b0089a352c65fe55e875de7caae/hosts.txt#L1209C6-L1209C6

Commondreams.org is a pretty hardcore progressive site and does not belong on a no-qanon blacklist. Please fix.

**Comment by rimu** [comment]
It's removed now. Thanks!
