### ISSUE TITLE
Rawstory leftist site on a no-qanon blacklist?

### ISSUE THREAD

**Issue by ScarylePoo** [rimu/no-qanon#58]
https://github.com/rimu/no-qanon/blob/9041c43819836b0089a352c65fe55e875de7caae/hosts.txt#L1215C7-L1215C7

So I have found 4 sites so far that are progressive or leftist sites that are on a no-qanon blacklist. I am starting to get the feeling that this list is not well maintained nor is it trustworthy.

**Comment by rimu** [comment]
It's removed now. Thanks!
