### ISSUE TITLE
French blocklist

### ISSUE THREAD

**Issue by GreatWizard** [rimu/no-qanon#59]
### Current situation

I don't know what happened but the quality about french list is questionable.
I didn't go into the whole listing about the french websites but some recent updates make no sense.

The principle to this list is 
> An anti-fascist domains block-list of QAnon, conspiracy, fake news, far-right and discriminatory websites.

And we have some official french government website like
- je-mengage.fr website on how to enroll in french army

Political (or related to political) middle-right/right website
- parti-renaissance.fr
- en-marche.fr
- amisdenicolassarkozy.fr

All this are clearly unrelated to conspiracy, fake news, far-right and discriminatory websites.
It's more opinion from an individual and should NOT be in that list.

### Moving forward

Can we take times to clean the french listing?
Do you need any help from French people?

**Comment by NotaInutilis** [comment]
https://www.slate.fr/story/220095/pourquoi-souvent-militaires-officiers-gendarmes-groupes-ultradroite-terrorisme-extreme-droite
https://www.liberation.fr/politique/decivilisation-de-la-societe-macron-adoubee-par-la-droite-et-lextreme-droite-20230526_I3V7ZDHVL5FW5D74VZQ47GTERI/

Just a couple random sources. The army is and always has been a radicalization machine that preys on the vulnerable to use them as cannon fooder/a state violence tool. The current French president is an integral part of the current far right pipeline who likes Maurras and Pétain. Both are known to spread false information. It's not a coincidence that Le Pen got so far in the latests elections.

Sarkozy should be in prison, no reason to defend him and his friends.

The French right wing is full of awful racists (islamophobes, transphobes, etc.) who gladly applaud actual fascists and promote their ideas. They are bad actors that spread harmful discourse and actually do harm to the marginilized.

Believe it or not but I actually pondered the question. But looking at social sciences and investigative journalism, all I could say was: fuck 'em, they go. They are clearly related to conspiracy, fake news, far-right and discriminatory websites.

Anti-fascism has to happen before fascism, and it does not include protecting conservatives and neoliberals that enable it.

**Comment by rimu** [comment]
Where to draw the line is sometimes difficult, especially when evaluating foreign (to me) websites, and I lack immersion in the relevant cultural context (France). I do feel a bit uncomfortable about getting involved in non-english domains.

**Comment by rimu** [comment]
@NotaInutilis let's discuss this privately before proceeding further.

**Comment by NotaInutilis** [comment]
@rimu Sure. How do we get in touch? Can't find any private message button here.

**Comment by rimu** [comment]
@NotaInutilis let's try Matrix: https://matrix.to/#/!WBAvrqNLZbbdUPPKgO:matrix.org?via=matrix.org

**Comment by NotaInutilis** [comment]
@rimu finally found the id for my matrix account but getting a "[403] You are not invited to this room." error when trying to join
