### ISSUE TITLE
Telsa.com

### ISSUE THREAD

**Issue by jaredcat** [rimu/no-qanon#64]
`tesla.com` and `www.tesla.com` should be removed from this list.
This causes issues with my car and app.

I subscribed to this list to block qanon but i see you have a `tycoons` folder. I think this should be out of scope for this repo and kind of confusing when stuff that are not related to qanon are being blocked.

Breaking up these lists into more granular repos will let people more easily find lists based on those topics they might want to block and make them more trustworthy lists.

**Comment by rimu** [comment]
I agree and have removed most of the tycoons folder. Thanks for bringing this up!
